### PR TITLE
CI to build README

### PR DESCRIPTION
**Pull request by colevandersWands**
👋 Hello @jackdoe, @unmeshvrije just showed me this repo.  It's pretty cool.  

Maybe this little action will make your work easier! If you're interested I could update it to build the book.pdf as well

### CODE REVIEW

**Comment by colevandersWands** [comment]
👋 Hello @jackdoe, @unmeshvrije just showed me this repo.  It's pretty cool.  Maybe this little action will make your work easier! If you're interested I could update it to build the book.pdf as well

**Comment by jackdoe** [comment]
oh thats great, it will be great if the pdf is built automatically as well.

at the moment i use vscode markdown to pdf, and i style it a bit with style.css but actually i have to do a lot of work to format it like a real book.

for now i am just pushing content every day so i have it ready for the next day.

I cant wait when we get to git with my daughter to show her how someone contributed to the book :)

-b

**Comment by colevandersWands** [comment]
Is this the extension you use?  I'll try reverse-engineering the important bits to keep your styling.  https://github.com/yzane/vscode-markdown-pdf

Have you ever seen [Git and GitHub for Poets](https://thecodingtrain.com/beginners/git-and-github/)?  It covers git/hub and collaboration with a little poem instead of code.  Plus Dan is great.

**Comment by jackdoe** [comment]
yea, this is the extension; but dont worry too much about the styling, i think for now any pdf will be ok.

thanks for the git for poets, i will check it

**Pull request merged**
