### PR TITLE
CI to build book.pdf after README.md

### PR DESCRIPTION
**Pull request by colevandersWands**
The style configuration isn't working, I've probably missed something simple but it's a start.

### CODE REVIEW

**Comment by jackdoe** [comment]
THANKS!

**Comment by colevandersWands** [comment]
Was there a problem with the script I could fix, or is it just not something you wanted after all?

**Comment by jackdoe** [comment]
no problem with it, its just the book.pdf is 5mb and i felt its gonna make the repo too big as i commit few times per day
i will bring it back after i measure if the diff of the pdf compresses well so it doesnt blow up the size

**Comment by colevandersWands** [comment]
Makes sense.  since keeping it up to date isn't so important the VSCode extension is a simpler way

**Pull request merged**
